# Custom Language File for Launcher Customizer

[ejs.app]
title = "DMB"

[ejs.landing]
mediaGitHubURL = "https://damp11113.xyz/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://git.damp11113.xyz/Mirror/unknow-dmb"
supportLink = "https://damp11113.xyz/donate"

[ejs.welcome]
welcomeHeader = "Welcome to DMB Project"
welcomeDescription = "Hello world!"
welcomeDescCTA = "Hello world!"
