# Custom Language File for Launcher Customizer

[ejs.app]
title = "Unknow DMB"

[ejs.landing]
mediaGitHubURL = "https://git.damp11113.xyz/Mirror/unknow-dmb"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://git.damp11113.xyz/Mirror/unknow-dmb"
supportLink = "https://damp11113.xyz/donate"

[ejs.welcome]
welcomeHeader = "Welcome to Unknow-DMB Project"
welcomeDescription = "Hello world!"
welcomeDescCTA = "Hello world!"
